# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_status', models.CharField(choices=[(b'success', b'Transaction successful.'), (b'pending', b'Transaction in progress.'), (b'fail', b'Transaction failed.'), (b'initial', b'Transaction initialized.')], default=b'initial', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('merchant_config', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EasyPayPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Payment')),
                ('payment_token', models.CharField(blank=True, help_text=b'EasyPay generated token in case of OTC transactions', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text=b'EasyPay generated Order ID (only for Mobile Account)', max_length=50, null=True)),
                ('transaction_expiry_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('payments.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentMethod'),
        ),
    ]
