# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
