# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_gallery_gallery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='organization',
            field=models.CharField(max_length=100),
        ),
    ]
