# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20171012_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='personal_web_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
