# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_speaker18'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker18',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
