# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-03 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_speaker18_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='conference_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
