# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-03 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_speaker_conference_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker18',
            name='site',
        ),
        migrations.DeleteModel(
            name='Speaker18',
        ),
    ]
