# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0011_auto_20181003_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
