# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models


def update_data_in_speakers(apps, schema):
    for speaker in apps.get_model('theme', 'Speaker').objects.all():
        speaker.name = speaker.title
        speaker.sort_order = speaker.pk
        speaker.save()


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_speaker_github_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='speaker',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(update_data_in_speakers)
    ]
