# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_auto_20181004_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='created',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='site',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='title',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='updated',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True),
        ),
    ]
